const data = [
  {
    foodName: "Pizza Magharita",
    foodType: "Pizza",
    foodStyle: "Neopolitan",
    rating: 5,
    img: "https://upload.wikimedia.org/wikipedia/commons/a/a3/Eq_it-na_pizza-margherita_sep2005_sml.jpg",
    price: 20.5,
    key: 0,
    quantity: 1,
  },
  {
    foodName: "Big Boy Burger",
    foodType: "Burger",
    foodStyle: "American",
    rating: 3.5,
    img: "https://assets.bonappetit.com/photos/5b919cb83d923e31d08fed17/1:1/w_2560%2Cc_limit/basically-burger-1.jpg",
    price: 10.5,
    key: 1,
    quantity: 1,
  },
  {
    foodName: "Fully Loaded Fries",
    foodType: "Fries",
    foodStyle: "American",
    rating: 4.5,
    img: "https://upload.wikimedia.org/wikipedia/commons/8/83/French_Fries.JPG",
    price: 11,
    key: 2,
    quantity: 1,
  },
  {
    foodName: "Evian Water",
    foodType: "Drink",
    foodStyle: "Drink",
    rating: 1,
    img: "https://assets.sainsburys-groceries.co.uk/gol/7856691/1/640x640.jpg",
    price: 6,
    key: 3,
    quantity: 1,
  },
  {
    foodName: "Full English",
    foodType: "Basic",
    foodStyle: "English",
    rating: 5,
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRLMNT8jKdEld3qyFGGetiTYo8fWAK7CTH5Eg&usqp=CAU",
    price: 16.5,
    key: 4,
    quantity: 1,
  },
  {
    foodName: "Proud Pasta Pesto",
    foodType: "Pasta",
    foodStyle: "Italian",
    rating: 3,
    img: "https://recipetineats.com/wp-content/uploads/2019/02/Pesto-Pasta_2-1.jpg",
    price: 11.5,
    key: 3.5,
    quantity: 1,
  },
];

export default data;
